apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zsy8jyjj3-nodejs
  janus-idp.io/tekton: zsy8jyjj3-nodejs
  backstage.io/kubernetes-id: zsy8jyjj3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zsy8jyjj3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
